# Definition
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hellotypes.foo.com
spec:
  group: foo.com
  version: v1
  scope: Namespaced
  names:
    kind: HelloType
    plural: hellotypes
    singular: hellotype
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["message"]
          properties:
            message:
              type: "string"
# HelloType
---
apiVersion: foo.com/v1
kind: HelloType
metadata:
  name: hello1
spec:
  message: hello world