// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package template_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestEngineClient is the client API for TestEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestEngineClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
	Hello(ctx context.Context, in *BasicMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type testEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewTestEngineClient(cc grpc.ClientConnInterface) TestEngineClient {
	return &testEngineClient{cc}
}

func (c *testEngineClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/template_engine.TestEngine/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testEngineClient) Hello(ctx context.Context, in *BasicMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/template_engine.TestEngine/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestEngineServer is the server API for TestEngine service.
// All implementations must embed UnimplementedTestEngineServer
// for forward compatibility
type TestEngineServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	Hello(context.Context, *BasicMessage) (*StringMessage, error)
	//mustEmbedUnimplementedTestEngineServer()
}

// UnimplementedTestEngineServer must be embedded to have forward compatible implementations.
type UnimplementedTestEngineServer struct {
}

func (UnimplementedTestEngineServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedTestEngineServer) Hello(context.Context, *BasicMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedTestEngineServer) mustEmbedUnimplementedTestEngineServer() {}

// UnsafeTestEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestEngineServer will
// result in compilation errors.
type UnsafeTestEngineServer interface {
	mustEmbedUnimplementedTestEngineServer()
}

func RegisterTestEngineServer(s grpc.ServiceRegistrar, srv TestEngineServer) {
	s.RegisterService(&TestEngine_ServiceDesc, srv)
}

func _TestEngine_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestEngineServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template_engine.TestEngine/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestEngineServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestEngine_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestEngineServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template_engine.TestEngine/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestEngineServer).Hello(ctx, req.(*BasicMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// TestEngine_ServiceDesc is the grpc.ServiceDesc for TestEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "template_engine.TestEngine",
	HandlerType: (*TestEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TestEngine_Echo_Handler,
		},
		{
			MethodName: "Hello",
			Handler:    _TestEngine_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
