# permissions for end users to edit hellotypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hellotype-editor-role
rules:
- apiGroups:
  - foo.com.kubekuiderht
  resources:
  - hellotypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foo.com.kubekuiderht
  resources:
  - hellotypes/status
  verbs:
  - get
